# Generated by Django 4.2.24 on 2025-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('color', models.CharField(blank=True, max_length=256, null=True)),
                ('memory', models.CharField(blank=True, max_length=256, null=True)),
                ('vendor', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.CharField(blank=True, max_length=128, null=True)),
                ('original_price', models.CharField(blank=True, max_length=128, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=256, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=256, null=True)),
                ('diagonal', models.CharField(blank=True, max_length=128, null=True)),
                ('resolution', models.CharField(blank=True, max_length=128, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestItem',
        ),
    ]
