# Generated by Django 4.2.24 on 2025-09-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_product_delete_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='full_name',
        ),
    ]
