# Generated by Django 4.2.24 on 2025-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_rename_title_product_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_name',
            new_name='title',
        ),
    ]
