# Generated by Django 4.2.24 on 2025-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
