# Generated by Django 4.2.24 on 2025-09-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_product_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
