# Generated by Django 4.2.24 on 2025-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
