# Generated by Django 4.2.24 on 2025-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
