# Generated by Django 4.2.24 on 2025-09-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_product_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
