# Generated by Django 4.2.24 on 2025-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
