# Generated by Django 4.2.24 on 2025-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diagonal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
